# Generated by Django 6.0.7 on 2026-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Projekttitel')),
                ('projektnummer', models.CharField(max_length=50, unique=True, verbose_name='Projektnummer')),
                ('status', models.CharField(choices=[('idee', 'Projektidee'), ('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('abgeschlossen', 'Abgeschlossen'), ('verzug', 'in Verzug'), ('problem', 'Problem')], default='idee', max_length=20)),
                ('startdatum', models.DateField(blank=True, null=True, verbose_name='Projektbeginn')),
                ('enddatum', models.DateField(blank=True, null=True, verbose_name='vorauss. Projektende')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['titel'],
            },
        ),
    ]
