# Generated by Django 6.0.7 on 2026-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('project_number', models.CharField(max_length=50, unique=True, verbose_name='Project Number')),
                ('status', models.CharField(choices=[('idea', 'Project Idea'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('behind', 'behind Schedule'), ('problem', 'Problem')], default='idea', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Planned Start')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Planned End')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Projekt',
        ),
    ]
