# Generated by Django 6.0.7 on 2026-08-05 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_delete_projekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Stage Name')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='Short Name')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_ce_ivd_only', models.BooleanField(default=False, verbose_name='CE-IVD Only')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='project',
            name='actual_end',
            field=models.DateField(blank=True, null=True, verbose_name='Actual End'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_start',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Start'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_problem',
            field=models.BooleanField(default=False, verbose_name='Problem Reported'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_description',
            field=models.TextField(blank=True, verbose_name='Problem Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Project Group'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, max_length=150, verbose_name='Project Manager'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Project Idea'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='idea', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20)),
                ('responsible_person', models.CharField(blank=True, max_length=150, verbose_name='Responsible Person')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Planned Hours')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Actual Hours')),
                ('planned_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Planned Material Cost')),
                ('actual_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Material Cost')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Planned Start')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Planned End')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Actual Start')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Actual End')),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='main.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_entries', to='main.developmentstage')),
            ],
            options={
                'ordering': ['stage__order'],
                'constraints': [models.UniqueConstraint(fields=('project', 'stage'), name='unique_project_stage')],
            },
        ),
    ]
