# Generated by Django 6.0.7 on 2026-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_developmentstage_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('general', 'General Development Project'), ('ivd', 'IVD Kit')], default='general', max_length=20, verbose_name='Project Type'),
        ),
    ]
