# Generated by Django 6.0.7 on 2026-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentstage',
            name='code',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
