# Generated by Django 6.0.7 on 2026-08-07 10:02

from django.db import migrations


STAGES = [
    {
        "code": "project-idea",
        "name": "Project Idea",
        "order": 1,
    },
    {
        "code": "market-research",
        "name": "Market and Literature Research",
        "order": 2,
    },
    {
        "code": "intended-use",
        "name": "Intended Use",
        "order": 3,
    },
    {
        "code": "proof-of-principle",
        "name": "Proof of Principle",
        "order": 4,
    },
    {
        "code": "risk-analysis",
        "name": "Risk Analysis",
        "order": 5,
    },
    {
        "code": "laboratory-development",
        "name": "Laboratory Development",
        "order": 6,
    },
    {
        "code": "verification",
        "name": "Verification of Specifications",
        "order": 7,
    },
    {
        "code": "specification-sheet",
        "name": "Documentation: Specification Sheet",
        "order": 8,
    },
    {
        "code": "instruction-for-use",
        "name": "Documentation: Instruction for Use",
        "order": 9,
    },
    {
        "code": "kit-validation",
        "name": "Kit Validation",
        "order": 10,
    },
    {
        "code": "validation-report",
        "name": "Documentation: Validation Report",
        "order": 11,
    },
    {
        "code": "market-launch",
        "name": "Market Launch",
        "order": 12,
    },
    {
        "code": "post-market-surveillance",
        "name": "Post Market Surveillance",
        "order": 13,
    },
]


def create_stages(apps, schema_editor):
    DevelopmentStage = apps.get_model(
        "main",
        "DevelopmentStage",
    )

    for stage_data in STAGES:
        DevelopmentStage.objects.update_or_create(
            name=stage_data["name"],
            defaults={
                "code": stage_data["code"],
                "order": stage_data["order"],
            },
        )


def remove_stages(apps, schema_editor):
    DevelopmentStage = apps.get_model(
        "main",
        "DevelopmentStage",
    )

    codes = [stage["code"] for stage in STAGES]

    DevelopmentStage.objects.filter(
        code__in=codes
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_developmentstage_code'),
    ]

    operations = [
        migrations.RunPython(
            create_stages,
            remove_stages,
        ),
    ]