# Generated by Django 6.0.7 on 2026-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20260807_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentstage',
            name='code',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
