# Generated by Django 6.0.7 on 2026-08-13 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_developmentstage_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_stage_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.projectstage')),
            ],
        ),
    ]
