# Generated by Django 6.0.7 on 2026-08-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projectstageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Work Step')),
                ('order', models.PositiveIntegerField(default=0)),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Planned Start')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Planned End')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Actual Start')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Actual End')),
                ('notes', models.TextField(blank=True)),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_steps', to='main.projectstage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
